### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by MartinHammarstedt** [PGijsbers/admonitions#2]
Thank you for developing this plugin! Would it be possible to add support for Python 3.9? As far as I can tell, the only 3.10 feature you are using is the `str | None` syntax. If that is the case, Python 3.9 support could be added simply by including `from __future__ import annotations` at the top of `admonition.py`.

The reason I'm asking is that in my current project we aim to support all the currently maintained Python versions, which includes 3.9 for another year.

**Comment by PGijsbers** [comment]
Sure! I'll add it this week.

**Comment by PGijsbers** [comment]
New release available on the repository, probably on PyPI tomorrow.

**Comment by MartinHammarstedt** [comment]
Great, thank you for solving this so quickly!

**Comment by PGijsbers** [comment]
The release is now on PyPI. I would appreciate it if you let me know if everything seems to work as expected. Cheers!

**Comment by MartinHammarstedt** [comment]
I’ve tested it with Python 3.9, and it seems to work perfectly. Thanks again for the quick fix!
